apply plugin: 'com.android.application'

android {
    compileSdkVersion 34
    defaultConfig {
        applicationId "com.android.support"
        minSdkVersion 21
        //noinspection ExpiredTargetSdkVersion
        targetSdkVersion 29
        versionCode 1
        versionName "4.0"
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
        // here i excluded theme azl and DZ 
        buildConfigField "boolean", "INCLUDE_THEME_AZL", "false"
        buildConfigField "boolean", "INCLUDE_THEME_DZ", "false"

    }
    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            shrinkResources false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        ndkBuild {
            path file('src/main/jni/Android.mk')
        }
    }
    namespace 'com.android.support'
}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
gradle.projectsEvaluated {
    def manualBuildConfig = file("src/main/java/com/android/support/BuildConfig.java")
    if (manualBuildConfig.exists()) {
        println "Deleting manual BuildConfig.java for Gradle build"
        manualBuildConfig.delete()
    }
}